# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/bullhead/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),bullhead)

# Home button animation (Pixel SystemUI)
include $(CLEAR_VARS)
LOCAL_MODULE := SystemUIGoogle
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := SystemUI
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_OWNER := google
LOCAL_DEX_PREOPT := false
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

# Pixel Settings
include $(CLEAR_VARS)
LOCAL_MODULE := SettingsGoogle
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := Settings
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_OWNER := google
LOCAL_DEX_PREOPT := false
LOCAL_SRC_FILES := $(LOCAL_MODULE)/apps/.apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

# Pixel SetupWizard
include $(CLEAR_VARS)
LOCAL_MODULE := SetupWizard
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := SetupWizard
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_OWNER := google
LOCAL_DEX_PREOPT := false
LOCAL_SRC_FILES := $(LOCAL_MODULE)/apps/.apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

# Pixel Sounds Package
PIXEL_SOUND_RESOURCE_DIR := $(LOCAL_PATH)/sounds-pixel

PIXEL_SOUND_RESOURCES := $(patsubst $(PIXEL_SOUND_RESOURCE_DIR)/%,%,$(shell find $(PIXEL_SOUND_RESOURCE_DIR) -type f -o -type l))

define install-sound-files
include $$(CLEAR_VARS)
LOCAL_MODULE := $(2)$(1)
$(info $(LOCAL_MODULE))
LOCAL_MODULE_TAG := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_STEM := $(1)
LOCAL_PATH := $(3)
LOCAL_MODULE_PATH := $$(TARGET_OUT)/media/audio
LOCAL_MODULE_OWNER := google
LOCAL_SRC_FILES := $(1)
include $$(BUILD_PREBUILT)
endef

$(foreach fp, $(PIXEL_SOUND_RESOURCES),\
  $(eval $(call install-sound-files,$(fp),Pixel,$(PIXEL_SOUND_RESOURCE_DIR))))

include $(CLEAR_VARS)
LOCAL_MODULE := PixelSoundResources
LOCAL_REQUIRED_MODULES := $(foreach pn,$(PIXEL_SOUND_RESOURCES),Pixel$(pn))
LOCAL_MODULE_OWNER := google
include $(BUILD_PHONY_PACKAGE)

endif
